name: Build cv
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Copy resume.md to working directory
        run: cp content/resume.md $GITHUB_WORKSPACE
      - name: Build PDF
        uses: docker://pandoc/core:2.9
        with: 
          args: "resume.md --output=cv.pdf"
        working-directory: $GITHUB_WORKSPACE
