name: Build cv
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Copy resume.md to working directory
        run: cp content/resume.md .
      - name: Build PDF
        uses: docker://pandoc/latex:latest
        with: 
          args: "resume.md --output=cv.pdf"
