name: Build cv
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Build PDF
        uses: docker://pandoc/core:2.9
        with: 
          args: "content/resume.md --output=content/cv.pdf"
