name: Build cv
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy content from repository
        uses: actions/checkout@v3
      - name: Compile PDF
        uses: docker://pandoc/latex:latest
        with:
           args: --output=cv.pdf content/resume.md
      - name: Copy output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: cv.pdf

    # defaults:
    #   run:
    #     working-directory: ${{ github.workspace }}
    # steps:
    #   - name: Checkout repo
    #     uses: actions/checkout@v2.3.4
    #   - name: Copy resume.md to working directory
    #     run: cp content/resume.md .
    #   - name: Build PDF
    #     uses: docker://pandoc/latex:latest
    #     with: 
    #       args: "resume.md --output=cv.pdf"
    #   #- name: Move PDF to content folder
    #   # run: mv -f cv.pdf content/cv.pdf
    #   - name: Copy output
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: output
    #       path: output/test.pdf
